### ISSUE TITLE
Change default behaviour after removing a relation to other/foreign sign

### ISSUE THREAD

**Issue by ocrasborn** [Woseseltops/signbank#11]
When deleting an entry in one of the tables Relation to Other Signs / Relation to Foreign Signs, the system exits the edit mode and collapses the pane where the relations are. Change to staying in edit mode, and keeping open the Relations pane.

**Comment by ocrasborn** [comment]
+ do the same for the deletion of entries in the Morphology table.

**Comment by Woseseltops** [comment]
This turned out to be a matter of simply adding something like '?editrel' to the redirect url. However, it took me quite a while to figure this out, as well as WHERE this redirect was defined in the code.
