### ISSUE TITLE
Change menu options under 'Definitions/Notes'

### ISSUE THREAD

**Issue by ocrasborn** [Woseseltops/signbank#13]
1) Adapt to contain only the following, in this order:

Note
Private note
To do
Suggestion for other gloss

2) Change column header 'Role' to 'Type'
3) Reveal Checkmark under first column (Published); it seems to be hidden now
4) Rename panel to just 'Notes', removing 'Definitions/'

**Comment by Woseseltops** [comment]
Did 1, 2 and 4. I wasn't able to replicate 3, though, for me it's always there in both Chrome and Firefox.

**Comment by richardbank** [comment]
The checkmark is hidden for me as well... (both in FF and Chrome, on Win7)

**Comment by ocrasborn** [comment]
Still hidden in Safari as well. From the Safari debugger:
----------------------------------------------
   <table class='table'>
      <tr>
          <th style='width:1em'></th>
          <th style='width:3em'>Published</th>
          <th style='width:3em'>Index</th>
          <th style='width:10em'>Type</th>
          <th>Text</th>
      </tr>
    
    </table>
----------------------------------------------

and:

----------------------------------------------
    <form id='add_definition' action='/dictionary/update/definition/2172' method="POST">
        <fieldset>
        <input type='hidden' name='csrfmiddlewaretoken' value='7Rq5tQGLc7LNnfAFKkIwUqwL3EFFdP8J' />
         <table class='table'>
            <tr>
                <td style='width:5em'><input class='form-control' name='count' type='number'></td>   
                <td style='width:10em'><select class="form-control" id="id_role" name="role">
<option value="" selected="selected">---------</option>
<option value="note">Note</option>
<option value="privatenote">Private Note</option>
<option value="todo">To Do</option>
<option value="sugg">Suggestion for other gloss</option>
</select></td>
                <td><input class='form-control' name='text' placeholder='Enter new note'></td>
            </tr>
----------------------------------------------

**Comment by Woseseltops** [comment]
Aaaah. This is not a browser issue but a communication issue :) . 

Your code showed me that you're not talking about editing notes (which I was referring to), but to adding new ones. There, indeed, no checkmark is visible. I'll add it.

**Comment by Woseseltops** [comment]
Done.
