### ISSUE TITLE
The menu bar is unorganized

### ISSUE THREAD

**Issue by Woseseltops** [Woseseltops/signbank#2]

**Comment by Woseseltops** [comment]
For the reader's understanding: in the Django admin, there are pages 'named' '/signs/dictionary/', '/signs/search/', and feedback/overview. Previously, when going to the corresponding URLs (like http://signbank.science.ru.nl/signs/dictionary), the content of these pages was displayed.

This is not what we wanted; instead of manually created pages with texts, these links should go to existing Signbank functionality. I achieved this by hardlinking these urls to the views of this functionality, in this file: https://github.com/Woseseltops/signbank/blob/master/signbank/urls.py . For example, the URL '/signs/dictionary/' was linked to the view signbank.dictionary.views.search (just like the URL '/dictionary/', which is now no longer visible in the menu).

The original pages still exist in the Django admin so the correct links will be displayed in the menu bar, but the content on these pages is no longer accessible.

As a sidenote: this is not the prettiest solution. A better one would be to create functionality so that pages could be either of the 'display content' type or of the 'display functionality' type. If the user chooses the last one, s/he can pick a Django view to display. I felt this might be a bit of an overkill for our purposes, though.

**Comment by ocrasborn** [comment]
Vet!

met de beste wensen voor 2015,

Onno
