### ISSUE TITLE
Add 'Save and edit next' button next to 'Save' in edit mode

### ISSUE THREAD

**Issue by ocrasborn** [Woseseltops/signbank#22]
By 'next', I mean the next Annotation ID gloss (sorted from A-Z), not the ID number.

**Comment by Woseseltops** [comment]
Done, and as I was busy with these button, I also moved the delete button to the left, like we discussed yesterday.

**Comment by ocrasborn** [comment]
save + edit next werkt bij mij niet — bij jou wel?

Nu je er toch mee bezig bent, is het misschien goed om meteen maar Issue #64 (cancel button) erbij te maken, zou je dat nog willen doen?

Groet,
Onno

**Comment by Woseseltops** [comment]
> save + edit next doesn't work for me, does it work for you?

Yes, on Linux both in Firefox and Chrome. What part doesn't work for you? 

Note that Chrome might be a bit misleading: if you change a to b, hit 'Save and edit next', and then use the 'Previous' button in your browser, it will show a again. If you refresh, it will show b, like you'd expect.

**Comment by ocrasborn** [comment]
It was on Safari on my Macbook, can't reproduce it on Safari on my desktop.
