### ISSUE TITLE
Some keyword/translation links lead to error

### ISSUE THREAD

**Issue by ocrasborn** [Woseseltops/signbank#26]
Search for keyword 'wij': both 'wij' and 'wij tweeën' lead to error page. Didn't test many others.

**Comment by Woseseltops** [comment]
Accidently fixed this one while working on #5. Indeed related, @richardbank

**Comment by Woseseltops** [comment]
Note to self: this still isn't fully fixed. For example, search for 'abbe' and see what happens.

**Comment by ocrasborn** [comment]
(Probably redundantly: When I try to change the keyword for the item ABBE-DE-L'EPEE to Abbé de l'Épée (with accents): similar error)

**Comment by Woseseltops** [comment]
Fixed my own observation, but I'm not sure whether i fixed yours, @ocrasborn . As far as I can see, you can change keywords all you want, with or without accents, and you won't get an error.

**Comment by richardbank** [comment]
The problem popped up again, in two places:
- in the import-csv-function, when either the old or the new value contains a unicode char 
- in the Django admin interface, when trying to delete an old (unused) keyword containing unicode chars

**Comment by richardbank** [comment]
Addition to my previous comment:
It looks like the error in the import-csv-function is thrown by the script that checks for differences, not the script that applies them (which makes sense considering that changing keywords in the UI works without error).
However, when a plain old value (e.g. italie) should be replaced by a unicode one (e.g. italië), no error is thrown, the link to the old value is deleted, but the new value is **not** imported.

**Comment by Woseseltops** [comment]
So to summarize: it doesn't work for both algorithms, but the detection algorithm complains about it, while the update algorithm does not.

**Comment by richardbank** [comment]
Yes (I tried to be descriptive :-)
Plus, I get errors when I try to add e.g. italië as a keyword in the UI (but not always...)

**Comment by Woseseltops** [comment]
I changed a number of things, and I can now:
* Add an remove keywords with weird chars in the admin
* Use the import function to change keywords without weird chars to something with weird chars (italie -> italië)
* Use the import function to change keywords with weird chars to something without weird chars (italië -> italie)
* Use the import function to change keywords with weird chars to something else with weird chars (italië -> itälie)

Fixed?

**Comment by richardbank** [comment]
Fixed for the greatest part. At first it looked as if nothing had changed (when importing italië, old keyword italie was deleted, new one not added). What fixed the problem was to save the to-be-imported file as UTF-8 instead of Windows-1252. It may well be that this could have been the solution all the time. So the import-function is fixed (hooray!)

However, the unicode problem popped up in yet another place: the dictionary view (go to dictionary view, click a, click Abbé de l'Épée, bingo.

**Comment by ocrasborn** [comment]
Related? Tried to change the order of the two keywords for MAAR: from 'let op, maar' to 'maar, let op'. Save led to error in Safari. Restarting Safari shows the altered order has been saved...

![screenshot 2015-04-26 11 59 57](https://cloud.githubusercontent.com/assets/10242207/7336733/62f42590-ec0c-11e4-9a7d-2687bc23534f.png)

**Comment by richardbank** [comment]
It's a different kind of error, but I can confirm on Chrome/Win8.1. 

Note, however, Onno, that when you make these changes, they will be overwritten next time I import the keywords column from Anique's file.

**Comment by Woseseltops** [comment]
I fixed the Unicode problem mentioned by @richardbank (I wonder how long these problem will keep popping up) , and made a separate issue for the problem mentioned by @ocrasborn : https://github.com/Woseseltops/signbank/issues/58
