### ISSUE TITLE
Search page only loads for superusers

### ISSUE THREAD

**Issue by ocrasborn** [Woseseltops/signbank#27]
Empty page with header (image + menu bar) and footer appears

**Comment by richardbank** [comment]
Display of search page is a access rights issue. Only superusers can see it, it is not enough for any other user to just have all permissions assigned.

**Comment by Woseseltops** [comment]
Small mistake, solved almost by accident. If you are a superuser, or have the 'Can search' permission, or are in a group with that permission, you can now access the search page. If not, you cannot.
