### ISSUE TITLE
Create page under menu item Signs > New Sign

### ISSUE THREAD

**Issue by ocrasborn** [Woseseltops/signbank#28]
• Menu item & function should only be visible to user roles 'editor' and 'publisher'
• Currently, the only way to create a new sign is to click the button bar above the search results (?!)
• The two-step approach is fine: first enter a few basic (gloss) fields, then click 'Add Sign', then proceed to editing all fields. Advantage: it can be checked right at the star that both the field "Annotation ID Gloss: Dutch" and the field "Annotation ID Gloss: English" contain unique values.
• Fields that appear in this first step should be "ID Gloss", "Annotation ID Gloss: Dutch", and "Annotation ID Gloss: English". Enforce that the latter two contain unique values!
• Upon confirmation, user should be sent to the Detail View of the new entry, with the Edit mode enabled, so that movie can be uploaded and other information can be filled. All panes should be expanded rather than closed (also for the screen that follows the other 'New Sign' button)

**Comment by Woseseltops** [comment]
Done, except for:

> Enforce that the latter two contain unique values!

Shouldn't that be the former two? So 'ID gloss' and 'Annotation ID Gloss: Dutch' should be unique, while 'Annotation ID Gloss: English' doesn't have to be?

**Comment by ocrasborn** [comment]
No: the Annotation gloss fields are unique identifiers, while 'ID Gloss' is used to lemmatise multiple ID glosses (e.g. phonological variants) under a single lexical entry -- or that's how we currently plan to use it.

**Comment by ocrasborn** [comment]
Is the uniqueness of the two fields actually correctly enforced elsewhere? What is the feedback message users get to see?

**Comment by Woseseltops** [comment]
> No: the Annotation gloss fields are unique identifiers

Alrighty, built in an extra check.

> Is the uniqueness of the two fields actually correctly enforced elsewhere? What is the feedback message users get to see?

No, I looked it up in the code. The only thing that's unique is the sign id, you can happily change anything else into anything you want. Sound like a new Github issue?
