### ISSUE TITLE
Limit access to some menu items

### ISSUE THREAD

**Issue by ocrasborn** [Woseseltops/signbank#30]
1) Only users in the groups Editor and Publisher should be able to see the following menu items (and load the corresponding pages):
• Signs > Dictionary view
• Signs > New sign
• Feedback > Feedback overview
2) Only users in the Publisher group should be able to see the following menu items (and load the corresponding pages):
• Signs > Import CSV

**Comments**
1) Hiding the menu item altogether for some users would be most elegant; alternative would be to display a page 'You do not have sufficient access rights to access this page." In the latter case: please remove the Dictionary view menu item altogether: we don't want to raise the impression to users without an account that our database is a dictionary.
2) Double-check how this is managed in the Auslan Signbank; does our redesign of the menu bar conflict with how the user management was set up in Django? Or can the CSV_Import page be added to the Django list of functions so that we can manage user rights there?
3) The "Dictionary view" menu item is now loadable without being logged in, but any query will lead to "There is no exact match to the word you typed." Is this because the search is set to match 'full string' rather than 'starts with' (and we don't have single letters as keywords)? Or is access otherwise blocked?

**Comment by Woseseltops** [comment]
Note to self, the next steps should be:
* Change the Page model to include more than one group.
* In menu generation, get the group of the current user
* Check if the group of the user is in the group_required list of the page

**Comment by Woseseltops** [comment]
Done! I discovered there was already a stub in place: you could specify a single 'required group' for each user page in the Django admin. I 
* changed this to field where you can select more required groups for a page
* added that these pages don't show if the user is not in one of the specified groups
* added that the corresponding menu items don't show either
* used this new system for the four pages mentioned in the description
