### ISSUE TITLE
Circular reference in Relations to Other Signs

### ISSUE THREAD

**Issue by susanodd** [Woseseltops/signbank#331]
The Gloss MAAKT-NIET-UIT has a Homonym with itself in panel Relations to Other Signs.

**Comment by susanodd** [comment]
I adjusted the Gloss Detail View to ignore circular Homonyms.
(This is in the branch that hasn't been merged yet, with the Minimal Pairs panel.)
Perhaps it ought to be checked when the user wants to add a relation to another sign that it's not circular?
There may exist other circular relations in the database. The MAAKT-NIET-UIT I happened to find.
A warning could be shown in the Relations to Other Signs.

**Comment by ocrasborn** [comment]
Good point @susanodd . I've removed this one, but we should check to avoid the creation of new ones. Incidentally: what happens if we remove a sign that is involved in a reference, are the relations to this sign in other entries automatically deleted?

**Comment by susanodd** [comment]
Good question! I will find out.

**Comment by susanodd** [comment]
It looks like deletion is done within the database django python code. (Code supporting signbank, in django/db/models/deletion.py and django/db/models/query.py etc.)

I found that I was not able to delete a sign from within Gloss Detail View, in spite of there being a button for this when editing the sign. The code expects to jump back to Admin List View (admin_gloss_list) but that didn't work because I wasn't at an Admin page.

I need to figure out what the control flow ought to be. I wasn't able to delete a sign to check.

It should just be that relations of a deleted sign also get deleted (by the underlying database python code). It seems that some data is stored about deleted information. There are also two different kinds of permissions: can_delete_unpublished, can_delete_published.
We probably need to confirm whether these are checked for in the appropriate places.

**Comment by susanodd** [comment]
Yes, deleting a gloss also deletes relations involving it.

**Comment by ocrasborn** [comment]
:-)

**Comment by vanlummelhuizen** [comment]
@ocrasborn @susanodd Can this issue be closed?

**Comment by susanodd** [comment]
This seems to have been repaired but never closed.
