### ISSUE TITLE
Add field "Virtual object" (LocVirtObj)

### ISSUE THREAD

**Issue by ocrasborn** [Woseseltops/signbank#37]
• Add text field "Virtual object". This is intended as a specification of one of the values of "Initial Primary Location" (yet to be renamed to "Location"). Maximum size 50 char.
• In detail view, present under Location in the Phonology tab.
• In search interface: present to the right of the Location field
(Related to #35, another modification to the data model)

**Comment by Woseseltops** [comment]
Done:
* Added to data model
* Added to Django admin
* Added to normal web view
* Made editable
* Added to search
* Added to export and import
