### ISSUE TITLE
Add field 'Semantic field' under panel Semantics

### ISSUE THREAD

**Issue by ocrasborn** [Woseseltops/signbank#39]
• field code SemField
• Include in Search panel Semantics as well
• Add an initial choice list on the basis of the present Auslan tags, see list below [Task for Onno]

                  'daystf': 'semantic:day',
                  'deaftf': 'semantic:deaf',
                  'animalstf': 'semantic:animal',
                  'arithmetictf': 'semantic:arithmetic',
                  'artstf': 'semantic:arts',
                  'bodyprtstf': 'semantic:bodypart',
                  'carstf': 'semantic:car',
                  'citiestf': 'semantic:city',
                  'clothingtf': 'semantic:clothing',
                  'colorstf': 'semantic:color',
                  'cookingtf': 'semantic:cooking',
                  'drinkstf': 'semantic:drink',
                  'eductf': 'semantic:education',
                  'familytf': 'semantic:family',
                  'feeltf': 'semantic:feel',
                  'foodstf': 'semantic:food',
                  'furntf': 'semantic:furniture',
                  'govtf': 'semantic:government',
                  'groomtf': 'semantic:groom', 
                  'healthtf': 'semantic:health',
                  'judgetf': 'semantic:judge',
                  'langactstf': 'semantic:language act',
                  'lawtf': 'semantic:law',
                  'materialstf': 'semantic:material',
                  'metalgtf': 'semantic:metalg',
                  'mindtf': 'semantic:mind',
                  'moneytf': 'semantic:money',
                  'naturetf': 'semantic:nature',
                  'numbertf': 'semantic:number',
                  'ordertf': 'semantic:order',
                  'peopletf': 'semantic:people',
                  'physicalactstf': 'semantic:physical act',
                  'qualitytf': 'semantic:quality',
                  'quantitytf': 'semantic:quantity',
                  'questsigntf': 'semantic:question',
                  'recreationtf': 'semantic:recreation',
                  'roomstf': 'semantic:rooms',
                  'saluttf': 'semantic:salutation',
                  'sensestf': 'semantic:sensing',
                  'sextf': 'semantic:sexuality',
                  'shapestf': 'semantic:shapes',
                  'shoppingtf': 'semantic:shopping',
                  'sporttf': 'semantic:sport',
                  'telecomtf': 'semantic:telecommunications',
                  'timetf': 'semantic:time',
                  'traveltf': 'semantic:travel',
                  'utensilstf': 'semantic:utensil',
                  'weathertf': 'semantic:weather',
                  'worktf': 'semantic:work',

**Comment by Woseseltops** [comment]
As far as I can see, these choices are not in the admin yet, which is more or less necessary to start on this issue. Could you let me know here when you're done?

Also let me know when I can automate something for you. If you really want to add all of these fields, a quick script to do so is probably much more efficient.

**Comment by ocrasborn** [comment]
Added choices in admin

**Comment by Woseseltops** [comment]
Done:
* Added to data model
* Added to Django admin
* Added to normal web view
* Made editable
* Added to search
* Added to export and import
