### ISSUE TITLE
Video not visible in Public view

### ISSUE THREAD

**Issue by ocrasborn** [Woseseltops/signbank#43]
- Videos are only visible in the Detail view, not in the Public view; they should be.
- Note: the public view is only used for logged in users now (of any group), so the public view is not 'public' in the sense of being accessible to user Anonymous (this would constitute the dictionary version we may open up in the future)

**Comment by Woseseltops** [comment]
It's visible now. Do we also want it centered and larger, as I saw in some other Signbank?

**Comment by ocrasborn** [comment]
Yes please!

**Comment by Woseseltops** [comment]
Done (forgot to label this commit: https://github.com/Woseseltops/signbank/commit/359408a8f901cc42eec7f113d427eec7e53c3060

**Comment by Woseseltops** [comment]
Note: the image 'no video available' is still small

**Comment by ocrasborn** [comment]
We leave the 'no video' image small as it is; to revise should we open the site to the public.
