### ISSUE TITLE
Ability to add additional videos in a separate panel

### ISSUE THREAD

**Issue by ocrasborn** [Woseseltops/signbank#47]
Goal: allow for storing videos related to a lexical entry that were recorded for earlier studies/other databases/specific experiments. Initial purpose: include videos of Merel created for Ellen Ormel's VENI project.
* Create a panel "Other videos" at the bottom of the detail view
* Add a table with one video reference per row. Columns:
     1. Video type (field values editable in Django; initial values: Alternative citation form, Citation form with mouthing, Sign in sentence context; VENI Ellen);
     2. Alternative gloss (text field; editable; values need not be unique);
     3. File name after upload (to be filled in by the system)
* Allow for uploading of a new video; assigning it a file name that starts with the "annotation ID gloss" and the database number (like the present file names for the 'standard videos') followed by a dash and the full type name without spaces. Example: BUITEN-D-1087-VENIEllen.mp4, where the type value that the user entered is "VENI Ellen".
* A hyperlink on the file name should lead to downloading the file. We will later think about nicer visualisations (see also #49)

**Comment by ocrasborn** [comment]
Wessel, is this explicit enough?

**Comment by Woseseltops** [comment]
Under the hood, the OtherVideo model is now defined. You can already see it, and add 'virtual' videos in the admin (no upload functionality yet). 

Next up:
* Show existing OtherVideos in the detail view.
* Add possibility to edit OtherVideos in the detail view.
* Add possibility to add OtherVideos in the detail view, and force a video upload.

Questions so I understand a little better what I am building: 
* What would be the use of the 'alternative gloss' field?
* Each OtherVideo will be coupled to one gloss, correct?

**Comment by ocrasborn** [comment]
Answers:
• The 'alternative gloss' should be optional: it reflects potentially different ways of referring to the sign that was used in earlier projects or other projects from which the videos stem.
• Eh... no, I think: individual OtherVideos should be able to occur with multiple Annotation ID Glosses. This will be used in case we upload examples-in-sentence-context: the same sentence can be used to illustrate multiple lexical items.

**Comment by Woseseltops** [comment]
You can now view and edit OtherVideos in the gloss detail view (editing added in commit with wrong issue id https://github.com/Woseseltops/signbank/commit/93c0afaef975889c54178a5b5b97626d1f4b0f77) . Next up: adding new ones

**Comment by Woseseltops** [comment]
Adding new other videos is now almost done. Things I still need to do:
* Test it on other places
* Make it so that the other videos panel opens automatically when you've added a new video, so you can quickly add another one.

And after that, I also need to add deleting other videos.

**Comment by ocrasborn** [comment]
Test for gloss/3270: I can add one, but may not specify the type as N/A, even though it is in the list. Leads to various error messages.

**Comment by Woseseltops** [comment]
>  but may not specify the type as N/A

Good find, now you can. 

Also, the other video panel now automatically reopens when you just added a video, and I already added the trash cans to delete a video when in edit mode.

**Comment by Woseseltops** [comment]
You closed this a bit too early, as you couldn't actually delete other videos yet; now you can :)

**Comment by ocrasborn** [comment]
:-)
