### ISSUE TITLE
Hide the menu item and page 'Proposed new signs'/'Recently added signs' for anonymous users

### ISSUE THREAD

**Issue by ocrasborn** [Woseseltops/signbank#474]

**Comment by Woseseltops** [comment]
For the ASL Signbank, I have selected some required groups in the admin for these pages. As anonymous (=not logged in) user, you are in no group, so you don't see the 'Proposed new signs' and 'Recently added signs' pages. At the global Signbank it was already like this.

**Comment by Woseseltops** [comment]
Happy @ocrasborn ?
