### ISSUE TITLE
Switch searching for Tags back on

### ISSUE THREAD

**Issue by ocrasborn** [Woseseltops/signbank#48]

**Comment by Woseseltops** [comment]
Done, good one. You can now use both search field simultaneously, which was previously impossible.

**Comment by Woseseltops** [comment]
Whoops, the #48 in this commit should be #71

**Comment by Woseseltops** [comment]
A check before I start: I plan to implement this as we did relations. That is, you can select a type of tag (like 'needs video'), and then only signs remain that have that tag. 

The alternative would be to be able to select multiple tags, and then only signs remain that have this combination of tags. As there are no examples of this on the current search page, I would have to build this from scratch, which would take longer.

Agreed to go with the first approach?

**Comment by ocrasborn** [comment]
Then of course the more flexible the better :-)

**Comment by Woseseltops** [comment]
Done. If needed, you can select multiple tags by holding ctrl (or shift, it's similar to how you select files in your OS).
