### ISSUE TITLE
The CSV export is broken

### ISSUE THREAD

**Issue by Woseseltops** [Woseseltops/signbank#5]

**Comment by Woseseltops** [comment]
This were two problems in one. At the one hand, the exported fields didn't match the ones we wanted any longer, at the other, the csv export was scared of some of the Dutch weird chars (ë è).

**Comment by richardbank** [comment]
Entries with 'Dutch weird characters' are not exported correctly ('Abbé de l'Épée' turns up as 'Abbe de l'Ã‰pÃ©e', 'tweeën' turns into 'tweeÃ«n'

**Comment by richardbank** [comment]
Sorry, forget I said that, 'Dutch wierd characters' are correctly exported. Excel is the troublemaker here.

**Comment by ocrasborn** [comment]
Boolean fields do not appear to be exported at all, but remain empty. Any value (T/F, True/False, 1/0) would be OK.

**Comment by Woseseltops** [comment]
I fixed this two weeks ago :) https://github.com/Woseseltops/signbank/commit/fcd93798801ed765abffce332650443990a5575c Could it be the case that you are using an older export? And if not, what fields are we talking about?

**Comment by ocrasborn** [comment]
Sorry, my fault! Looking at an old export indeed.

**Comment by Woseseltops** [comment]
No problem :)
