### ISSUE TITLE
The django admin crashes for gloss #ok

### ISSUE THREAD

**Issue by Woseseltops** [Woseseltops/signbank#50]
AttributeError at /admin/dictionary/gloss/2889/
'object' object has no attribute 'split'

**Comment by Woseseltops** [comment]
I can no longer reproduce this (Firefox / Chrome); if I go to the specified, it shows as I'd expect. Did we maybe accidently fix this earlier?

**Comment by ocrasborn** [comment]
Same here, works OK. Close.

**Comment by richardbank** [comment]
I noticed before that the problem is gone. So apparently, you fixed it 
accidentaly :-)

Wessel Stoop schreef op 19-6-2015 om 10:29:
