### ISSUE TITLE
Add search field for english Gloss

### ISSUE THREAD

**Issue by ocrasborn** [Woseseltops/signbank#54]
field annotation_idgloss_en

**Comment by ocrasborn** [comment]
I started adding this where I want to have it: top of the search page, between igloss and keywords. To do:
1) Change style sheet so that the three fields are the same size
2) Make it work :-) -- there's something i overlooked such that it currently has no effect.

**Comment by Woseseltops** [comment]
Fixed both content and workings :) . Have a look athe commits if you want to see how.
