### ISSUE TITLE
Add fields to Frequency panel

### ISSUE THREAD

**Issue by ocrasborn** [Woseseltops/signbank#56]
Field 1: "Number of Occurrences"
Field 2: "Number of Signers"
(to contain corpus frequencies not split out over regions)

Plus add to search page. Both in the detail view and on the search page they should be at the top of the region-specific frequencies.

See #55, #19

**Comment by Woseseltops** [comment]
Done for the detail view, but not for the search page, as we don't have the option to search for frequency (yet?). If we want that, maybe:
* We should wait for #19 first, as having real data will make testing easier :).
* We should agree on how it should work first. Searching for signs with exact frequency x doesn't seem that useful to me, so maybe some functionality where you can select 'more than' and 'less than'?
