### ISSUE TITLE
Changing the keywords from the website leads to an error in some cases

### ISSUE THREAD

**Issue by Woseseltops** [Woseseltops/signbank#58]
@ocrasborn : "Tried to change the order of the two keywords for MAAR: from 'let op, maar' to 'maar, let op'. Save led to error in Safari. Restarting Safari shows the altered order has been saved... Tried the same (altering the order) in Firefox/Mac: generates same error, but pops up a more gentle error message that I can click away. If I try to add a keyword (to MAART-C): same error."

![](https://cloud.githubusercontent.com/assets/10242207/7336733/62f42590-ec0c-11e4-9a7d-2687bc23534f.png)

**Comment by Woseseltops** [comment]
Hmm... I can't reproduce this :( . I even tried it on a Mac! Could you specify what I have to do to get this error step by step?

**Comment by ocrasborn** [comment]
Can't reproduce it now either. Will try to remember my steps better next time :-)
