### ISSUE TITLE
The search functionality doesn't use the Dutch fields yet

### ISSUE THREAD

**Issue by Woseseltops** [Woseseltops/signbank#6]

**Comment by ocrasborn** [comment]
1) Also change the grouping of search fields to the following ones:
• Language, Basic properties
• Phonology
• Semantics
• Relations to other and foreign signs
• Publication status, Notes
2) Change the Show/Hide links following the search group label to a hyperlink on the label itself

**Comment by Woseseltops** [comment]
Already works for most of our fields; I'll do the rest next week.

**Comment by Woseseltops** [comment]
Searching for related signs (both in the same language and foreign) started to take way too much time, so I kept them simple on purpose; they're not used in the current database anyway.

**Comment by Woseseltops** [comment]
Removed the separate links to show and hide, only the 'Publication Status and Notes' part left.

**Comment by ocrasborn** [comment]
For the relations: would it be easy to create a search for 'any sign with a homonym [antonym, synonym, etc.] relation? And for the foreign signs: any sign with a relation to a foreign sign?

**Comment by ocrasborn** [comment]
See also #13

**Comment by ocrasborn** [comment]
Two fields don't appear in the Phonology search pane yet: "Repeated movement" and "Alternating movement"

**Comment by Woseseltops** [comment]
I've fixed repeated and alternating movement! 

The only thing left now is the section 'Publication status/notes'. I see there are a number of choices I have to make, and I'm not really sure what to do. A proposal:
* For the publication status, I only do 'Proposed new sign'; I think in 'In web dictionary' isn't really something people would look for (and right now, it's the same for all signs).
* For the notes, I only add the option to look for signs that have notes (as opposed to really searching for the text in the note and/or the role of the note). As far as I know the note system is barely used anyway.

Agreed?

**Comment by richardbank** [comment]
Me I would agree with only searching on 'Proposed new sign' in publication status, not on 'In web dictionary'.
As for Notes, searching for have/doesn't have a note would not be helpful, I guess, searching for the text of a note would. It may be barely used now, but we've only just begun :-)

**Comment by Woseseltops** [comment]
Allrighty, then I'll do it that way!

**Comment by ocrasborn** [comment]
Please also allow searching for 'in web dictionary' (or not). And as for the notes: please allow for a combination of criteria: a string in the notes field that can be restricted by also selecting the type of note.

**Comment by Woseseltops** [comment]
Added:
  * Search by whether the gloss is in the web dictionary (currently: all 'No').
  * Search by whether the gloss is a proposed new sign.
  * Search for glosses that have a note of a particular type. You can also select 'All', so you get all glosses that contain notes.
  * Search for glosses that have notes that contain a particular piece of text.

As for all search options, everything can be combined. So you can search for all glosses that are proposed new signs, have a 'To do' note with the text 'Ask Onno' :).

**Comment by Woseseltops** [comment]
By the way, Onno, you mixed up two labels. I changed so that it shows as you intended.
