### ISSUE TITLE
After editing multiple Translation equivalents, the field shows only one 

### ISSUE THREAD

**Issue by richardbank** [Woseseltops/signbank#70]
When editing multiple (comma-separated) Translation equivalents in Dutch, after clicking the OK button, only one translation is shown. After leaving Edit mode, still only one translation is shown. Only after refreshing the page, all translations are shown.
(note: if you edit the translations again before refreshing the page, only the shown translation can be edited)

**Comment by Woseseltops** [comment]
Ah, apparently, I didn't completely clean up the mess I made for #64 . It was only a visual thing (as you already discovered, it saved correctly in the database), but I can imagine this is highly confusing. It now works again!
