### ISSUE TITLE
Change behaviour after searching for 'Translations' with the menu bar box

### ISSUE THREAD

**Issue by ocrasborn** [Woseseltops/signbank#71]
The Gloss and Translation search fields in the menu bar now lead to different visualisations: the gloss field hits appear in a detail view, the translation (keyword) field hits lead to the dictionary search results. Please change so that both result in the detail view (as created for the Gloss search in #24).

**Comment by Woseseltops** [comment]
Done in commit https://github.com/Woseseltops/signbank/commit/4fe534d13e045ab2ae26511a6982cd6591e9b7d6 (gave it the wrong issue number), good one. You can now also use both search boxes in the menu bar simultaneously, which was previously impossible.
