### ISSUE TITLE
Store metadata on new entries

### ISSUE THREAD

**Issue by ocrasborn** [Woseseltops/signbank#72]
Store the date of creation and the user that created the new entry, to then then use that to display a list of recently added items (#73, #74).

**Comment by ocrasborn** [comment]
If date and/or user is already stored for older items, then we can use that for the existing ones, but as most were imported in one go, it'd be fine if we all assign them user 'system' or something like that and date 1 Jan 2015.

**Comment by Woseseltops** [comment]
Done: both user and creation date are now saved with the gloss, and are visible from the detail view and the admin view. The existing glosses have no author and a creation date 1 Jan 2015. I will talk about the recently added page in issue #74

**Comment by Woseseltops** [comment]
( now also visible on signbank.science.ru.nl )
