### ISSUE TITLE
Add menu item Signs > Recently added

### ISSUE THREAD

**Issue by ocrasborn** [Woseseltops/signbank#74]
...with all entries created in the last 7 days. 
...leading to the standard list of search results, but
a) without the search fields on top
b) and with the added two fields at the left "Entry date" and "User name"
 See #72, #73

**Comment by Woseseltops** [comment]
Done, but not visible yet because of Ponyland upgrade

**Comment by Woseseltops** [comment]
( now also visible on signbank.science.ru.nl )

**Comment by ocrasborn** [comment]
• Change the contents of this page to all signs for which Proposed New Sign = True.
• Widen the columns so that the list better fills the page

**Comment by Woseseltops** [comment]
Done?

**Comment by ocrasborn** [comment]
Final touch: please remove the limit of showing only 20 items; just display all for which 'proposed new sign = true'

**Comment by Woseseltops** [comment]
![](http://gratitudeginteam.com/pics/ywiyc/your_wish_is_your_command_green_genie.jpg)

**Comment by ocrasborn** [comment]
http://www.google.nl/imgres?imgurl=http://brettmcfall.com/wp-content/uploads/2015/01/brettmcfall-lovetheboss.png&imgrefurl=http://brettmcfall.com/why-getting-a-better-paying-job-in-2015-is-the-biggest-mistake-you-could-ever-make/&h=700&w=600&tbnid=x2FS1F7m6xshSM:&docid=8nQH4LwcAmRK7M&ei=AGHxVZCTD4iwaorAkLgN&tbm=isch&client=safari&ved=0CDgQMygEMARqFQoTCJCT-LKm7McCFQiYGgodCiAE1w
