### ISSUE TITLE
Remove the SECRET_KEY from this repository

### ISSUE THREAD

**Issue by Woseseltops** [Woseseltops/signbank#789]
https://docs.djangoproject.com/en/dev/ref/settings/#secret-key

Found by Steven Loria

**Comment by susanodd** [comment]
There's even this exception in one of the django/conf files:

`raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")`

**Comment by vanlummelhuizen** [comment]
Fixed. `signbank/settings/server_specific/server_specific.py` is now a copied and altered version of the Global Signbank settings file.
