### ISSUE TITLE
The field choices should be editable from the Django admin

### ISSUE THREAD

**Issue by Woseseltops** [Woseseltops/signbank#8]

**Comment by Woseseltops** [comment]
Related to #7

**Comment by ocrasborn** [comment]
1) the order should also be editable in Django admin
2) an option to add separators between menu options would be useful (as we have some very long pull-down menus, like Handshape, which will appear messy when not sorted alphabetically)

**Comment by Woseseltops** [comment]
Seems to work now. It's not as straightforward as we had hoped, but it's something:

https://github.com/Woseseltops/signbank/wiki/How-to-add-new-field-choices-to-Signbank

**Comment by Woseseltops** [comment]
Now that I think of it, I want to give automating step 4, and possibly step 5, a try.

**Comment by ocrasborn** [comment]
If we edit/delete there, will values automatically be changed for all existing records?

**Comment by Woseseltops** [comment]
Yes and no. Field choices are not about database records themselves, but about how they are presented to the user. For example, for handedness, just the values 0-6 are saved in the database. Editing field choices tells Django that the value '3' should be displayed as '2a' , and the value '6' as 'X'. So changing a field choice should work, deleting one means that the machine value (so for handedness 0-6) would be displayed.

**Comment by Woseseltops** [comment]
Succes :D . I transformed the last two complicated steps into one easy one.
