### ISSUE TITLE
Repair virtual environment needed for .po compilation

### ISSUE THREAD

**Issue by ocrasborn** [Woseseltops/signbank#81]

**Comment by Woseseltops** [comment]
Done, turned out not to be that hard. What I did, for later reference:
* Upgrade pip: `pip install --upgrade pip`
* Recreate the virtualenv `virtualenv /www/signbank/live/virtualenv/signbank`

This recreates all parts of the virtualenv that were specific to Ubuntu 12, like the python executable.
