### ISSUE TITLE
Login page shows {%trans%} tags under Lost Password

### ISSUE THREAD

**Issue by henrinie** [Woseseltops/signbank#84]
At least when language chosen is English, Login page has the following text under 'Lost Password'.

{% trans "If you've lost or forgotten your password, enter your email address here and we'll reset it and send you a reminder." %}

**Comment by ocrasborn** [comment]
And here's another place where the {% trans %} shows in the interface: in the warning message I get upon clicking Delete Sign in the edit mode.
![screenshot 2015-09-21 16 26 29](https://cloud.githubusercontent.com/assets/10242207/9994472/af97a94a-607d-11e5-823c-43fd607151bb.png)

**Comment by Woseseltops** [comment]
Fixed, the problem was that there were newlines in the string in templates, which is allowed in html but not in Python.
