### ISSUE TITLE
Make 'recently_added' page accessible for logged-in users only

### ISSUE THREAD

**Issue by richardbank** [Woseseltops/signbank#85]
Page is currently visible for everyone, it should be visible only for users who are logged in. Ideally, this should be the page to land on after logging in for researchers/editors/publishers.

**Comment by Woseseltops** [comment]
The first part was easy; just a matter of some clicking in the admin. The landing page after logging seems extremely well hidden in the code.

**Comment by Woseseltops** [comment]
Ha! Success!
