### ISSUE TITLE
Setting language to nl when creating a new user leads to an error 

### ISSUE THREAD

**Issue by ocrasborn** [Woseseltops/signbank#88]
The only thing I can do to create a profile is to first save the new user with the default en filled in, then edit it to nl (for dutch users), then change back to en (for non-dutch users).

**Comment by Woseseltops** [comment]
I just tested this, and these are the results:
* Creating a new English user is simply a matter of creating a user, and not editing the user profile. (The editing we previously had to do was only for user that existed before the internationalization feature).
* It indeed does not work when you edit the results. Other people have the same problem, I'm going to try their solution later today or tomorrow:

http://stackoverflow.com/questions/12784830/django-user-creation-fails-in-the-admin-when-filling-profile-fields

**Comment by Woseseltops** [comment]
Fixed (https://github.com/Woseseltops/signbank/commit/233fa779f62743e412c1f4f60ad3ed16d554d781) . That link indeed contained the solution.
