### ISSUE TITLE
Editing the Annotation ID Gloss: English field leads to a display error

### ISSUE THREAD

**Issue by ocrasborn** [Woseseltops/signbank#90]
When I edit the Annotation ID Gloss: English, then switch of edit mode, the old and the new value appear separated by a comma. When I reload the page, it correctly shows only the new value. (replicable on Safari + Firefox, Mac)

**Comment by Woseseltops** [comment]
Is this the thing I already mentioned in #65 (first message by, second bullet)?

**Comment by ocrasborn** [comment]
Oh yes, right!

**Comment by Woseseltops** [comment]
Fixed (problem was an incorrectly parsed separator)
