### ISSUE TITLE
Create more space for field labels

### ISSUE THREAD

**Issue by richardbank** [Woseseltops/signbank#91]
When switching language to Dutch before logging in, the labels for the input fields become too large to fit in front of those fields:
![image](https://cloud.githubusercontent.com/assets/10399929/10131821/419f14c2-65d3-11e5-9d74-cbe26cd9b42c.png)
(This is likely to cause problems elsewhere as well)

**Comment by Woseseltops** [comment]
I never realized the login page was so messy! I alsways skip it automatically. I cleaned it up and made it a little prettier here and there. This is what it looks like right now for new users:

![signbank_login](https://cloud.githubusercontent.com/assets/1909317/10966902/fe831646-83b6-11e5-9463-5f6ef25c933e.png)

**Comment by ocrasborn** [comment]
Nice!
